name       : gnome-contacts
version    : 3.28.1
release    : 12
source     :
    - https://download.gnome.org/sources/gnome-contacts/3.28/gnome-contacts-3.28.1.tar.xz : f18f7fb87b3db9e7251caed5cef72fb3cb53c1837eec7b7d9a3308e170b7319e
license    : GPL-2.0-or-later
component  : office
summary    : Contacts is GNOME's integrated address book.
description: |
    Contacts is GNOME's integrated address book.
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(champlain-0.12)
    - pkgconfig(cheese-gtk)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(folks)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(goa-1.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libebook-1.2)
    - pkgconfig(libsecret-1)
    - pkgconfig(telepathy-glib)
    - docbook-xml
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
