name       : gnome-contacts
version    : 3.20.0
release    : 5
source     :
    - https://download.gnome.org/sources/gnome-contacts/3.20/gnome-contacts-3.20.0.tar.xz : bef88dc728aa7bb058c530fd936b262d96bbc17e73d640279842371bb3ad1588
license    : GPL-2.0
component  : office
summary    : Contacts is GNOME's integrated address book.
description: |
    Contacts is GNOME's integrated address book.
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(champlain-0.12)
    - pkgconfig(cheese-gtk)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(folks)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(goa-1.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libebook-1.2)
    - pkgconfig(libsecret-1)
    - pkgconfig(telepathy-glib)
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
