name       : gnome-contacts
version    : 3.18.0
release    : 2
source     :
    - https://download.gnome.org/sources/gnome-contacts/3.18/gnome-contacts-3.18.0.tar.xz : c81ad739a1f554e4c89979564565e32ceaf1d2cc6c93a6a75d929d7d1fe8e287
license    : GPL-2.0
summary    : Contacts is GNOME's integrated address book.
description: |
    Contacts is GNOME's integrated address book.
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(champlain-0.12)
    - pkgconfig(cheese-gtk)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(folks)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(goa-1.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libebook-1.2)
    - pkgconfig(libnotify)
    - pkgconfig(libsecret-1)
    - pkgconfig(telepathy-glib)
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
