name       : gnome-contacts
version    : 3.28.2
release    : 13
source     :
    - https://download.gnome.org/sources/gnome-contacts/3.28/gnome-contacts-3.28.2.tar.xz : 1c65ceff37d06ff7114b0d335f6c26e0f6bf1eff40af9feba73ad87cdfae8fc6
license    : GPL-2.0-or-later
component  : office
summary    : Contacts is GNOME's integrated address book.
description: |
    Contacts is GNOME's integrated address book.
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(champlain-0.12)
    - pkgconfig(cheese-gtk)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(folks)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(goa-1.0)
    - pkgconfig(libcanberra)
    - pkgconfig(libebook-1.2)
    - pkgconfig(libsecret-1)
    - pkgconfig(telepathy-glib)
    - docbook-xml
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
